# Generated by Django 2.1.7 on 2019-05-02 15:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfirmationModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirm_title', models.CharField(max_length=100)),
                ('confirm_desc', models.TextField(blank=True, null=True)),
                ('confirm_bool', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='QueueModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ReservationModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_id', models.CharField(max_length=10)),
                ('car_desc', models.TextField(blank=True, null=True)),
                ('car_type', models.CharField(choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL')], default='S', max_length=20)),
                ('serve_type', models.CharField(choices=[('บริการล้างสี + ดูดฝุ่น', 'บริการล้างสี + ดูดฝุ่น'), ('บริการเคลือบสีด้วย Quick Wax', 'บริการเคลือบสีด้วย Quick Wax'), ('บริการเคลือบสีด้วย Meguiar’s Synthetic Sealant 2.0 (เบอร์ 21)', 'บริการเคลือบสีด้วย Meguiar’s Synthetic Sealant 2.0 (เบอร์ 21)'), ('บริการเคลือบแก้ว', 'บริการเคลือบแก้ว')], default='บริการล้างสี + ดูดฝุ่น', max_length=255)),
                ('reserve_time', models.TimeField(null=True)),
                ('serve_time', models.TimeField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SatisfactionModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('satisfaction_title', models.CharField(max_length=100)),
                ('satisfaction_desc', models.TextField(null=True)),
                ('reservation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='carcare.ReservationModel')),
            ],
        ),
        migrations.AddField(
            model_name='queuemodel',
            name='reservation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='carcare.ReservationModel'),
        ),
        migrations.AddField(
            model_name='confirmationmodel',
            name='reservation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='carcare.ReservationModel'),
        ),
    ]
