# Generated by Django 2.1.7 on 2019-05-02 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carcare', '0002_deliverymodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverymodel',
            name='car_type',
            field=models.CharField(choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL')], default='S', max_length=20),
        ),
    ]
