# Generated by Django 2.1.7 on 2019-05-02 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carcare', '0003_deliverymodel_car_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverymodel',
            name='serve_time',
            field=models.DateTimeField(null=True),
        ),
    ]
