# Generated by Django 2.1.7 on 2019-05-02 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carcare', '0004_deliverymodel_serve_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliverymodel',
            name='reservation',
        ),
    ]
