# Generated by Django 2.1.7 on 2019-05-03 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carcare', '0007_auto_20190503_0356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservationmodel',
            name='serve_time',
        ),
        migrations.AddField(
            model_name='queuemodel',
            name='queue_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='queuemodel',
            name='serve_time',
            field=models.DateTimeField(null=True),
        ),
    ]
