# Generated by Django 2.1.7 on 2019-05-03 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carcare', '0008_auto_20190503_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='queuemodel',
            name='fininsh',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='confirmationmodel',
            name='confirm_bool',
            field=models.BooleanField(default=False),
        ),
    ]
