# Generated by Django 2.1.7 on 2019-05-04 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carcare', '0010_auto_20190504_1242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliverymodel',
            name='deliver_name',
        ),
        migrations.AddField(
            model_name='deliverymodel',
            name='car_id',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='deliverymodel',
            name='car_type',
            field=models.CharField(max_length=20),
        ),
    ]
