# Generated by Django 2.1.7 on 2019-05-04 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carcare', '0011_auto_20190504_1324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='queuemodel',
            name='queue_name',
        ),
    ]
