# Generated by Django 2.1.7 on 2019-05-04 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carcare', '0012_remove_queuemodel_queue_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queuemodel',
            name='car_type',
            field=models.CharField(choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL')], default='S', max_length=20),
        ),
        migrations.AlterField(
            model_name='queuemodel',
            name='reservation',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='carcare.ReservationModel'),
        ),
        migrations.AlterField(
            model_name='queuemodel',
            name='serve_type',
            field=models.CharField(choices=[('บริการล้างสี + ดูดฝุ่น', 'บริการล้างสี + ดูดฝุ่น'), ('บริการเคลือบสีด้วย Quick Wax', 'บริการเคลือบสีด้วย Quick Wax'), ('บริการเคลือบสีด้วย Meguiar’s Synthetic Sealant 2.0 (เบอร์ 21)', 'บริการเคลือบสีด้วย Meguiar’s Synthetic Sealant 2.0 (เบอร์ 21)'), ('บริการเคลือบแก้ว', 'บริการเคลือบแก้ว')], default='บริการล้างสี + ดูดฝุ่น', max_length=255),
        ),
    ]
