# Generated by Django 2.1.7 on 2019-05-04 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carcare', '0013_auto_20190504_1954'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='queuemodel',
            name='fininsh',
        ),
        migrations.AlterField(
            model_name='deliverymodel',
            name='serve_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='queuemodel',
            name='receive_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='queuemodel',
            name='reserve_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='queuemodel',
            name='serve_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reservationmodel',
            name='receive_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reservationmodel',
            name='reserve_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reservationmodel',
            name='serve_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='satisfactionmodel',
            name='satisfaction_desc',
            field=models.TextField(blank=True, null=True),
        ),
    ]
